format_version: 10
pipelines:
parameterstorecreate:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      ansible:
        git: https://github.com/NARENDRA935/aws-ssm-parameters.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - apply:
          fetch_materials: true
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: terraform
                    arguments: ["init"]
                - exec:
                    command: terraform
                    arguments: ["apply","-auto-approve"]


